### ISSUE TITLE
Minishell does not split commands by space after expanding a command name, but should

### ISSUE THREAD

**Issue by fan2bolide** [fan2bolide/minishell#5]
<img width="494" alt="Capture d’écran 2023-03-31 à 16 45 48" src="https://user-images.githubusercontent.com/82985749/229153478-52a54e8e-e726-43ad-a79e-652eb77945b6.png">

**Comment by aLeuleu** [comment]
Maybe split by space inside the convert_token_into_cmd_list if the token is an exec_name

**Comment by aLeuleu** [comment]
I'm having a hard time resolving this issue :
if i split by space inside the convert_token_into_cmd_list (case_token_is_an_exec_name),
commands like :
```export a="ls -lra"```
are interpreted like ```a="ls``` and ```-lra"``` are two seperated argument !
Maybe we should make sure that parameters that are between quotes are not splitted ! 

But then .. would'nt this conflict with the -removing quotes- part ? ...

**Comment by aLeuleu** [comment]
Splitting only the exec name (not the arg ! )
This is the way
