### ISSUE TITLE
parsing error (false positive)

### ISSUE THREAD

**Issue by aLeuleu** [fan2bolide/minishell#54]

**Comment by aLeuleu** [comment]
This parsing error pop whenever there is 6 or more pipes !

![Image](https://user-images.githubusercontent.com/97832618/231882796-2012c6ae-3256-4107-af41-14631e6f7ab9.png)

**Comment by fan2bolide** [comment]
fixed by commit f040beb (redefined OPEN_MAX to 10240 so linux can use it
