### ISSUE TITLE
cd: need to handle error for many arguments

### ISSUE THREAD

**Issue by fan2bolide** [fan2bolide/minishell#59]
<img width="297" alt="Capture d’écran 2023-04-14 à 20 44 23" src="https://user-images.githubusercontent.com/82985749/232130623-36f216bb-09aa-4f38-9cd0-60479c04aa92.png">

**Comment by aLeuleu** [comment]
@fan2bolide Please confirm you fixed this and close this issue

**Comment by fan2bolide** [comment]
oui aussi
