### ISSUE TITLE
cd & pwd need to handle absolute paths

### ISSUE THREAD

**Issue by fan2bolide** [fan2bolide/minishell#7]

**Comment by aLeuleu** [comment]
@fan2bolide : Could not reproduce the bug, please publish the buggy scenario

**Comment by fan2bolide** [comment]
<img width="418" alt="Capture d’écran 2023-03-31 à 19 54 52" src="https://user-images.githubusercontent.com/82985749/229194558-0532830a-6e69-4009-929f-9f8d63214701.png">

**Comment by aLeuleu** [comment]
ok, on it

**Comment by aLeuleu** [comment]
The goal is to achieve the same behaviour than bash, 
here is a list of commands that sum it all up :
```bash
bash-3.2$ mkdir -p a/b/c && cd a/b/c
bash-3.2$ rm -rf ../../../a
bash-3.2$ pwd && env | grep PWD
/Users/aurelienlevra/CLionProjects/minishell/a/b/c
OLDPWD=/Users/aurelienlevra/CLionProjects/minishell
PWD=/Users/aurelienlevra/CLionProjects/minishell/a/b/c
bash-3.2$ cd ..
cd: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
bash-3.2$ pwd && env | grep PWD
/Users/aurelienlevra/CLionProjects/minishell/a/b/c/..
OLDPWD=/Users/aurelienlevra/CLionProjects/minishell/a/b/c
PWD=/Users/aurelienlevra/CLionProjects/minishell/a/b/c/..
bash-3.2$ unset PWD
bash-3.2$ pwd && env | grep PWD
/Users/aurelienlevra/CLionProjects/minishell/a/b/c/..
OLDPWD=/Users/aurelienlevra/CLionProjects/minishell/a/b/c
```

**Comment by aLeuleu** [comment]
The real issue seems to be :
<img width="398" alt="Screenshot 2023-04-01 at 19 01 05" src="https://user-images.githubusercontent.com/97832618/229304480-8e0216ec-59a4-48de-aeac-67e62115e5df.png">
expected :
<img width="408" alt="Screenshot 2023-04-01 at 19 01 24" src="https://user-images.githubusercontent.com/97832618/229304496-61280086-2ce2-4cdb-afad-1138a151ba27.png">

**Comment by fan2bolide** [comment]
cd and pwd need to handle absolute paths

**Comment by aLeuleu** [comment]
Could not reproduce bug :

![Image](https://user-images.githubusercontent.com/97832618/229844493-94824055-6f6d-4e1e-854f-c07ba7960b3a.png)
