### ISSUE TITLE
first command does not execute inside a fork (export)

### ISSUE THREAD

**Issue by fan2bolide** [fan2bolide/minishell#8]
<img width="298" alt="Capture d’écran 2023-03-31 à 17 09 53" src="https://user-images.githubusercontent.com/82985749/229159291-30c64f18-8761-4090-ad9f-5a09ab39ee91.png">
<img width="349" alt="Capture d’écran 2023-03-31 à 17 10 03" src="https://user-images.githubusercontent.com/82985749/229159304-b3776c69-e2d4-405e-8edf-d9bc6de7e4d5.png">

**Comment by aLeuleu** [comment]
This is intereseting ! do you know why does bash behave like that ? I'm not sure of the logic behind that
